config/routes.rb
OmniauthPopup::Application.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    get '/sign_out' => 'sessions#destroy', :as => :sign_out

    resources :users, only: [:show, :index, :destroy]

    root to: 'pages#home'
  end

  get '*path' => redirect("/#{I18n.default_locale}/%{path}")
  get '' => redirect("/#{I18n.default_locale}")
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_with_omniauth(auth)
    user = find_by(auth.slice(:provider, :uid)) || initialize_from_omniauth(auth)
    user.update_dynamic_attributes(auth)
  end

  def self.initialize_from_omniauth(auth)
    new do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
    end
  end

  def update_dynamic_attributes(auth)
    self.image = auth.info.image if auth.info.image?
    self.save!
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  helper_method :current_user, :authenticate_user!

  private

  def set_locale
    I18n.locale = params[:locale] if params[:locale]
    # current_user.locale
    # request.env["HTTP_ACCEPT_LANGUAGE"]
    # request.remote_ip
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if !current_user
      # Example of forcing authentication with a certain provider.
      # Be aware of malicious redirects though.
      # http://blog.codeclimate.com/blog/2013/03/27/rails-insecure-defaults/#offsite-redirects
      origin = URI.parse(request.fullpath).path
      redirect_to "/auth/twitter?origin=#{origin}"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # Have a look at the info returned by the provider by uncommenting the next line:
    # render text: "<pre>" + env["omniauth.auth"].to_yaml and return
    omniauth = env['omniauth.auth']
    user = User.find_or_create_with_omniauth(omniauth)
    session[:user_id] = user.id
    flash[:notice] = t('controllers.sessions.create', provider: pretty_name(omniauth.provider))
    render_or_redirect
  end

  def failure
    flash[:alert] = t('controllers.sessions.failure', provider: pretty_name(env['omniauth.error.strategy'].name))
    render_or_redirect
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: t('controllers.sessions.destroy')
  end

  protected

  def render_or_redirect
    page = env['omniauth.origin']
    if env['omniauth.params']['popup']
      @page = page
      render 'callback', layout: false
    else
      redirect_to page
    end
  end

  def pretty_name(provider_name)
    provider_name.titleize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil if session[:user_id] == @user.id
    @user.destroy
    redirect_to root_url, notice: t('controllers.users.destroy')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_login_with(provider, url, html_options = {})
    add_default_class(html_options)
    convert_popup_attributes(html_options)

    link_to t('.login_with_link', provider: provider), url, html_options
  end

  private

  def add_default_class(html_options)
    default_class = "js-popup"

    if html_options.has_key?(:class)
      html_options[:class] << " " << default_class
    else
      html_options[:class] = default_class
    end
  end

  def convert_popup_attributes(html_options)
    width = html_options.delete(:width)
    height = html_options.delete(:height)

    if width && height
      html_options[:data] ||= {}
      html_options[:data].merge!({width: width, height: height})
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omniauth Popup</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class='main'>
    <h1><%= link_to 'Omniauth Popup', root_path %></h1>
    <nav class='lang-nav'>
      <span><%= t('.language') %>:</span>
      <ul class='lang-items'>
        <li class='lang-item'><%= link_to_unless_current 'English', locale: 'en' %></li>
        <li class='lang-item'><%= link_to_unless_current 'Português', locale: 'pt' %></li>
      </ul>
    </nav>
    <nav class='user-nav'>
      <ul>
        <% if current_user %>
          <li>
            <%= link_to current_user do %>
              <%= image_tag current_user.image, class: 'user-pic' if current_user.image %>
              <%= content_tag :span, current_user.name %>
            <% end %>
          </li>
          <li><%= link_to t('.logout_link'), sign_out_path %></li>
        <% else %>
          <li><%= link_to_login_with 'Facebook', '/auth/facebook', { width: '460', height: '460' } %></li>
          <li><%= link_to_login_with 'GitHub', '/auth/github', { width: '1050', height: '700' } %></li>
          <li><%= link_to_login_with 'Google', '/auth/google', { width: '800', height: '470' } %></li>
          <li><%= link_to_login_with 'Twitter', "/auth/twitter?lang=#{I18n.locale}", { width: '660', height: '710' } %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <div id='js-messages' class='messages'>
    <% flash.each do |type, message| %>
      <span class='message <%= type %>'>
        <%= message %>
      </span>
    <% end %>
  </div>

  <div class='content'>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<%= link_to t('.users_link'), users_path %>

app/views/users/index.html.erb
<h1><%= t('.title') %></h1>

<table class='users-table'>
  <tr>
    <th><%= User.human_attribute_name(:image) %></th>
    <th><%= User.human_attribute_name(:name) %></th>
    <th><%= User.human_attribute_name(:provider) %></th>
    <th><%= User.human_attribute_name(:uid) %></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.image %></td>
    <td><%= user.name %></td>
    <td><%= user.provider %></td>
    <td><%= user.uid %></td>
    <td><%= link_to t('.show_link'), user %></td>
    <td><%= link_to t('.destroy_link.text'), user_path(user), method: :delete, data: { confirm: t('.destroy_link.confirm') } %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p>
  <b><%= User.human_attribute_name(:name) %>:</b>
  <%= @user.name %>
</p>

<p>
  <b><%= User.human_attribute_name(:provider) %>:</b>
  <%= @user.provider %>
</p>

<p>
  <b><%= User.human_attribute_name(:uid) %>:</b>
  <%= @user.uid %>
</p>


<%= link_to t('.link_to_back'), users_path %>